# Generated by Django 5.1.7 on 2025-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tracks', models.IntegerField()),
                ('rotacao', models.CharField(max_length=4)),
                ('gramatura', models.CharField(max_length=4)),
                ('tamanho', models.CharField(max_length=6)),
                ('lancamento', models.DateField()),
                ('descricao', models.CharField(max_length=250)),
                ('preco', models.CharField(max_length=6)),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
