# Generated by Django 5.1.7 on 2025-04-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tracks', models.IntegerField()),
                ('rotacao', models.CharField(blank=True, max_length=4, null=True)),
                ('gramatura', models.CharField(blank=True, max_length=4, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=6, null=True)),
                ('lancamento', models.DateField()),
                ('descricao', models.CharField(max_length=250)),
                ('preco', models.CharField(max_length=6)),
                ('estoque', models.IntegerField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
                ('gravadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gravadora')),
            ],
        ),
        migrations.DeleteModel(
            name='Cd',
        ),
        migrations.DeleteModel(
            name='Disco',
        ),
    ]
