# Generated by Django 5.1.7 on 2025-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_formapagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rua', models.CharField(max_length=250)),
                ('NumeroCasa', models.IntegerField(max_length=8)),
                ('Bairro', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
                ('CEP', models.IntegerField(max_length=8)),
            ],
        ),
    ]
