# Generated by Django 5.1.7 on 2025-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='CEP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='NumeroCasa',
            field=models.IntegerField(),
        ),
    ]
